### ISSUE TITLE
`<class:Bot>': uninitialized constant Hipbot::Bot::Singleton (NameError)

### ISSUE THREAD

**Issue by MarioRuiz** [pewniak747/hipbot#20]
running the example code on the page i get this error:
`
C:/Ruby24/lib/ruby/gems/2.4.0/gems/hipbot-1.0.4/lib/hipbot/bot.rb:22:in `<class:Bot>': uninitialized constant Hipbot::Bot::Singleton (NameError)
Did you mean?  SignalException
	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/hipbot-1.0.4/lib/hipbot/bot.rb:19:in `<module:Hipbot>'
	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/hipbot-1.0.4/lib/hipbot/bot.rb:1:in `<top (required)>'
	from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/hipbot-1.0.4/lib/hipbot.rb:29:in `<top (required)>'
	from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
`

Last version of hipbot on Ruby 2.4, Windows 10

**Comment by steviee** [comment]
Got this as well.
